Repository InterviewExplorer/InterviewExplorer_back, pull requests merged in 2024-09, with the labels that each got.

#38 Feature/video landmarks overlay
  audio/0f1fe5a531474241b114951dafafb25f.mp3
  audio/358bebfce64f4804af9ad1d8b134e97f.mp3
  audio/ae300d31d97c4e61ab1ac71b2350820d.mp3
  audio/d468cf43ed874422bfc478abc1464a74.mp3
  main.py
  module/audio_extraction.py
  module/pose_feedback.py
Labels: Priority: Medium, Type: Feature

#39 Feature/rag4
  module/firstLLM.py
  module/rag.py
Labels: Priority: Critical, Type: Feature

#46 Feature/rag5
  main.py
  module/firstLLM.py
  module/rag.py
Labels: Priority: High

#50 Feature/check distance
  main.py
  module/audio_extraction.py
  module/check_distance.py
  module/pose_feedback.py
Labels: Priority: High, Type: Feature

#57 canGuideLine
  module/guide.py
Labels: Priority: Low

#58 Feature/check-distance
  main.py
  module/audio_extraction.py
  module/check_distance.py
  module/pose_feedback.py
Labels: Priority: Medium, Type: Feature

#62 캠 가이드라인 기능 추가
  main.py
  module/guide.py
Labels: Priority: Low

#65 Feature/pose feedback
  main.py
  module/audio_extraction.py
  module/check_distance.py
  module/pose_feedback.py
Labels: Priority: High, Type: Feature

#66 Feature/update feedback
  main.py
Labels: Priority: High, Type: Feature

#70 Feature/openai basic
  main.py
  module/openai_basic.py
Labels: Priority: Medium, Type: Feature

#71 이력서 기반 생성 질문 분리
  main.py
  module/openai_resumBehav.py
  module/openai_resumeTech.py
Labels: Priority: High

#76 Feature/openai basic
  main.py
  module/openai_basic.py
Labels: Priority: High, Type: Feature

#88 rag를 활용한 인성 면접 고도화 완료
  rag/rag_createNew.py
  rag/rag_new.py
Labels: Priority: High

#90 인성 면접 쿼리 수정 완료
  rag/rag_behavioral.py
  rag/rag_createNew.py
Labels: Priority: Medium, Type: Bug

#94 Feature/evn basic
  main.py
  rag/rag_createNew.py
  rag/rag_evaluateNew.py
  rag/rag_newB.py
Labels: Priority: High

#97 pdf요약정리
  main.py
  module/indexClear.py
  module/nori_test.py
  module/openai_pdf.py
  module/pdfSave.py
  module/pdfSearch.py
Labels: Priority: Critical

#100 Update/new q
  .idea/InterviewExplorer_back.iml
  .idea/misc.xml
  main.py
  module/openai_basic.py
  module/openai_each.py
  rag/rag_createNew.py
  rag/rag_evaluateNew.py
  rag/rag_newB.py
  requirement.txt
  requirements.txt
Labels: Priority: High, Type: Feature
