Repository InterviewExplorer/InterviewExplorer_back, pull requests merged in 2024-10, with the labels that each got.

#102 중복 질문 방지
  main.py
  module/openai_resumBehav.py
  module/openai_resumeTech.py
Labels: Priority: Medium

#112 꼬리질문 완료
  main.py
  module/openai_answerJudgment.py
  module/openai_answerOrganize.py
  rag/rag_followUp.py
Labels: Priority: High

#114 꼬리질문 평가 생성
  main.py
  rag/rag_followUp.py
Labels: Priority: Critical

#116 Feature/rag eva
  .DS_Store
  .gitignore
  main.py
  rag/rag_createNew.py
  rag/rag_evaluateNew.py
  rag/rag_newB.py
  requirements.txt
Labels: Priority: Critical, Type: Feature

#119 중복 문제 해결
  main.py
  module/openai_answerOrganize.py
Labels: Priority: High
